Get chat and channel id. Reply with new post price
paktusov/notifications_from_sahibinden pull request #2
Opened 2022-11-24 20:44 UTC by paktusov

2022-11-24 22:19 UTC, z268 requested changes
рефакторинг можно вынести в отдельную задачу

2022-11-24 22:19 UTC, z268 commented on bot/__main__.py
> +        format_new_price = f"{ad['history_price'][-1][0]:,.0f}".replace(',', ' ')
`ad['history_price'][-1][0]` 
не, ну в целом понятно конечно

2022-11-24 22:19 UTC, z268 commented on notifications_from_sahibinden/data.py
> +                new_price_ads.append(exist)
а чего бы сразу тут не отправить в телеграм?

2022-11-24 22:19 UTC, z268 commented on bot/__main__.py
> +            )
можно одинаковые аргументы вынести
```suggestion
        kw = dict(chat_id=channel_id, message_id=telegram_channel_message_id, parse_mode='HTML')
        if ad['thumbnailUrl']:
            bot.edit_message_caption(caption=caption, **kw)
        else:
            bot.edit_message_text(text=caption, **kw)
```

2022-11-24 22:19 UTC, z268 commented on bot/__main__.py
> +def make_caption(ad):
а если бы `ad` был бы pydantic моделью, тогда у него был бы

``` python
@property
def caption(self) -> str:
    return f'{self.link}\n{self.last_price} TL / {self.last_update:%d.%m.%Y %H:%M}'

@property
def link(self) -> str:
    return f'<a href="{site_config.host}{ad.url}">{self.title}</a>'

@property
def last_price(self) -> float:
    return f'{self.history_price[-1].price}'.replace(',', ' ')
```

2022-11-25 05:53 UTC, paktusov commented on bot/__main__.py
> +@bot.message_handler(content_types=['photo'])
тесты показали, что не вешает

2022-11-25 18:24 UTC, paktusov commented on notifications_from_sahibinden/data.py
> +                new_price_ads.append(exist)
там же задержка, хотел разделить эти процессы

2022-11-25 18:25 UTC, paktusov commented on bot/__main__.py
> +            )
это да, согласен

2022-11-25 18:25 UTC, paktusov commented on bot/__main__.py
> +@bot.message_handler(content_types=['photo'])
перепроверил, не вешает

2022-11-25 18:26 UTC, paktusov commented on bot/__main__.py
> +    if message.forward_from_chat and message.forward_from_chat.id == int(channel_id) and message.from_user.id == 777000:
он пока даже не очн помогает

2022-11-25 19:01 UTC, z268 commented on notifications_from_sahibinden/data.py
> +                new_price_ads.append(exist)
задержку нужно делать как-то иначе

2022-11-25 19:12 UTC, z268 commented on bot/__main__.py
> +@bot.message_handler(content_types=['photo'])
а такие варианты тоже не прокатывают? 
``` python
@bot.message_handler(content_types=['text', 'photo'])
```
или
``` python
@bot.message_handler(func=lambda message: True, content_types=['text', 'photo'])
```

на самом деле не принципиально, просто интересно. вроде в доке тоже по несколько декораторов навешивают на хендлеры

2022-11-25 19:13 UTC, z268 commented on bot/__main__.py
> +def record_ad_message_photo_id(message):
кажется название метода не соответствует содержимому. и `record` это глагол?

2022-11-25 19:51 UTC, paktusov commented on bot/__main__.py
> +@bot.message_handler(content_types=['photo'])
прокатывают

2022-11-25 19:52 UTC, paktusov commented on notifications_from_sahibinden/data.py
> +                new_price_ads.append(exist)
ну я пока складываю в очередь, а потом буду делать как-то иначе

2022-11-25 19:53 UTC, paktusov commented on bot/__main__.py
> +def record_ad_message_photo_id(message):
записывать - глагол

2022-11-25 21:46 UTC, z268 commented on bot/__main__.py
> +def record_ad_message_photo_id(message):
почему не save или update? и там же не photo_id записывается

2022-11-25 22:11 UTC, z268 commented on notifications_from_sahibinden/data.py
> +                new_price_ads.append(exist)
ощущение, что это нужно разбить логику на методы и сделать примерно такой алгоритм:
- получение объявлений из парсера, создание объектов pydantic модели (пусть будет ads)
- получение одним запросом всех ранее добавленных объявлений через IN и обновление необходимых полей в ads (history_price, last_updated)
- сохранение всех объектов ads, где внутри метода сохранения сделать проверку наличия старой цены в history_price и отправка либо коммента, либо нового сообщения

2022-11-26 08:43 UTC, paktusov commented on notifications_from_sahibinden/data.py
> +                new_price_ads.append(exist)
на новую ветку тянет, но сначала фича с картой.
а еще с удаленными объектами ворос, updatemany не отдает id объектов

2022-11-27 11:49 UTC, z268 approved these changes
провести последующий рефакторинг и переименовать get_telegram_message_id

2022-12-04 10:51 UTC, closed without merging