Mappoint
paktusov/notifications_from_sahibinden pull request #4
Opened 2022-12-04 20:35 UTC by paktusov

Add map image, extra add images and retry telegram API

2022-12-04 22:05 UTC, z268 requested changes
- [ ] дублирующийся код вынести в декоторатор
- [ ] можно заменить bs4 на pyquery

2022-12-04 23:02 UTC, z268 commented on deploy/app/Dockerfile
> +CMD ["poetry", "run", "celery", "-A", "app.tasks", "worker", "-B"]
а ты знаешь, что у тебя до этого celery запускалась с флагом `-B--loglevel=info` ?

2022-12-05 16:34 UTC, paktusov commented on deploy/app/Dockerfile
> +CMD ["poetry", "run", "celery", "-A", "app.tasks", "worker", "-B"]
Это я его поставил на этих выходных

2022-12-05 18:15 UTC, z268 commented on deploy/app/Dockerfile
> +CMD ["poetry", "run", "celery", "-A", "app.tasks", "worker", "-B"]
ты похоже не понял, там две аргумента склеились

2022-12-05 18:26 UTC, paktusov commented on deploy/app/Dockerfile
> +CMD ["poetry", "run", "celery", "-A", "app.tasks", "worker", "-B"]
а, запятую кто-то потерял

2022-12-05 18:32 UTC, z268 commented on bot/__main__.py
> +def retry_to_telegram_api(func):
слушай, ну действительно [похоже](https://github.com/eternnoir/pyTelegramBotAPI/blob/6373af78f3513199c62637e36f6f348622b94281/telebot/util.py#L656) )
еще бы добавить проверку на 429 код и не отличишь от метода из либы =)

2022-12-05 18:33 UTC, z268 commented on bot/__main__.py
> +def retry_to_telegram_api(func):
правда там не декоратором сделано

2022-12-05 18:37 UTC, z268 commented on bot/__main__.py
> +    url = f"{mapbox_config.url}/pin-l+0031f5({ad.lon},{ad.lat})/{ad.lon},{ad.lat},11,0/600x300?access_token={mapbox_config.token}"
может побольше карту? на компе мелковато

2022-12-10 15:56 UTC, merged